### ISSUE TITLE
cannot stat ‘bendict’: No such file or directory

### ISSUE THREAD

**Issue by menon92** [nitish94/bendict#1]
command `sudo make install` give the output : 
``` 
You must be root to install.
cp: cannot stat ‘bendict’: No such file or directory
make: *** [install] Error 1
```
I think **bnedict** file in master need to change

Thanks

**Comment by nitish94** [comment]
yes. I think I renamed it mistakenly. please change the script name and Install. I am fixing it now.

thanks for notify 

[fixed]

**Comment by menon92** [comment]
I install it by running `python3 BenDict.py` in terminal
